---
title: "Widow Care"
---

#### Resources for Widow Care

---

##### **Basic Widow Questionnaire** 

##### **(modified from [Widow Connection: Church Survey for Widow's Needs](https://widowconnection.com/resources/how-to-start-a-widows-ministry/))**

Years of being widow\_\_\_\_\_\_\_\_\_\_\_\_\_\_Age\_\_\_\_\_\_\_\_\_\_\_\_\_\_

Ages of children\_\_\_\_\_\_\_\_\_\_\_\_\_Do you attend this church?\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

What type of support are you receiving directly from close family?\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

What is your greatest need?\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

What is your greatest fear?\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

How can we help you?\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

Would you be interested in events for widows?  Rank preference, 1--low, 5-- high.

\_\_\_\_\_\_\_          Individualized Support

\_\_\_\_\_\_\_          Group Support/Discussion group (e.g. Griefshare)

\_\_\_\_\_\_\_          Bible study

\_\_\_\_\_\_\_          Social events at church like game nights or crafts

\_\_\_\_\_\_\_          Social outings off campus

\_\_\_\_\_\_\_          One time seminar of resources

Names and addresses of other widows who might benefit from this ministry: \_\_\_\_\_\_\_\_\_\_\_

What topics would you benefit from being included in studies, discussions, or resource materials?

---

##### **Christian Resources**

</br>

##### Articles

-   [Lifeway: 7 Ways to Care for Widows in Your Church](https://research.lifeway.com/2022/11/09/7-ways-to-care-for-widows-in-your-church/)

-   [Widow Connection: How to Start a Widows Ministry](https://widowconnection.com/resources/how-to-start-a-widows-ministry/)

</br>

##### Organizations

###### Listed in no particular order of precedence.

</br>

-   [A Widow's Might: Daily Christian Devotion for Women](https://awidowsmight.org/#/r-home "OUR VISION:  HELPING THOUSANDS OF WIDOWS DRAW OTHERS CLOSER TO CHRIST.")

    -   [About](https://awidowsmight.org/womens-christian-devotional/about-a-widows-might.html "About 'A Widow's Might'")

</br>

-   [Widow Connection](https://widowconnection.com/)

    -   [About](https://widowconnection.com/about-miriam/ "About 'A Widow's Might'")

</br>

-   [Triumphant 'N Treasured](https://triumphantntreasured.org/ "Encouragement Through Grief, Trauma, and Despair")

    -   Local Solutions

        -   Empower, Educate, Prepare: [Walk With a Widow](https://walkwithawidow.com/ "Goal of this organization "is to help Widows and Widowers find their “new normal” and to provide friends and family members with the information to support and embrace their loved ones."")

            -   [Emergency Kit and Support Docs](https://walkwithawidow.com/emergency-kit/ "Emergency Kit:  This is a great resource for most issues that a new widow will be confronted with. As a family member or friend, you can use this to help her in her time of need.  This is just a guide. We are not endorsing any particular service, and we ask that you seek advice from accountants and other professionals before making final decisions.")

                -   [Immediate Support for the Newly Widowed Needs Checklist](https://walkwithawidow.com/emergency-kit/immediate-support-for-the-newly-widowed-needs-checklist/)

                -   [Financial Checklist – Suggestions](https://walkwithawidow.com/emergency-kit/financial-checklist/)

    -   Global Solutions

        -   [Project Purple](https://triumphantntreasured.org/project-purple/ "Mission:    Our mission is to walk with these widows in their journey from poverty to royalty.  Triumphant ‘N Treasured establishes business initiatives to restore the dignity, community, and financial independence of impoverished widows.  We call this portfolio of businesses Project Purple, because we want to remind them that, contrary to what their societal norms say, they are daughters of the one true King and made to experience His love and care")

</br>

---

##### **Secular Resources**

</br>

##### Articles

-   [Psychology Today: 3 Things Widows Need](https://www.psychologytoday.com/us/blog/widows-walk/202211/3-things-widows-need)

</br>

##### Organizations

###### Listed in no particular order of precedence.

</br>

-   [Modern Widows Club](https://modernwidowsclub.org/ "Pioneers in solutions, support, and research for widows worldwide")

-   [Widows Connection](https://widowsconnection.org/ "Widowhood is hard work. You do not need to face it alone.  Losing your life partner is one of the most challenging transitions in a woman’s life.  Since our founding, we have helped over 10,000 women overcome the physical, emotional, and social challenges of widowhood, and find hope and fulfillment again in their lives.")

-   [The Widow Collaborative](https://thewidowcollaborative.com "Guidance, solutions and support for widows of any age who are navigating the complexities of life after losing a spouse or partner.")

    -   [About](https://thewidowcollaborative.com/about-us/)

---

##### Topics

Preparation

Coping with Grief

Support Systems

How to Help
